---
version: "2"

run:
  go: 1.24.6
  modules-download-mode: readonly

linters:
  enable:
    - zerolint
  settings:
    custom:
      zerolint:
        type: module
        description: "zerolint checks usage patterns of pointers to zero-size types."
        original-url: "https://fillmore-labs.com/zerolint"
        settings:
          level: "full"
          excluded:
            - "struct{}"
          generated: true
          match: "^.*$"
