---
version: "2"

run:
  go: 1.23.8
  modules-download-mode: readonly

linters:
  enable:
    - zerolint
  settings:
    custom:
      zerolint:
        type: module
        settings:
          full: false
          excluded: []
