---
run:
  go: "1.22.9"
  modules-download-mode: readonly
linters:
  enable:
    - zerolint
linters-settings:
  custom:
    zerolint:
      type: module
      settings:
        excluded: []
        basic: true
